substitutions:
  _MODULE_NAME: "moneycolfrontend"
  _VERSION: "0.9.0"
  _SHORT_SHA: "$SHORT_SHA"
  _DOCKERFILE_PATH: "/frontend/crema_template-2.0"
steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: bash
  args:
    - '-c'
    - |
    ls -lrt

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/${_MODULE_NAME}:${_VERSION}-${_SHORT_SHA}', '-f', '/workspace/${_DOCKERFILE_PATH}/Dockerfile', '/workspace/${_DOCKERFILE_PATH}' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/${_MODULE_NAME}:${_VERSION}-${_SHORT_SHA}']
images:
- 'eu.gcr.io/$PROJECT_ID/${_MODULE_NAME}:${_VERSION}-${_SHORT_SHA}'