substitutions:
  _MODULE_NAME: "moneycolfrontend"
  _VERSION: "0.8.0"
  _SHORT_SHA: "$SHORT_SHA"
  _DOCKERFILE_PATH: "/frontend"
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/${_MODULE_NAME}:${_VERSION}-${_SHORT_SHA}', '-f', '/workspace/${_DOCKERFILE_PATH}/Dockerfile', '/workspace/${_DOCKERFILE_PATH}' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/${_MODULE_NAME}:${_VERSION}-${_SHORT_SHA}']
images:
- 'eu.gcr.io/$PROJECT_ID/${_MODULE_NAME}:${_VERSION}-${_SHORT_SHA}'