micronaut:
  application:
    name: collections
  http:
    client:
      exception-on-error-status: false
  # https://micronaut-projects.github.io/micronaut-security/latest/guide/
  security:
    enabled: ${SECURITY_ENABLED:true}
    token:
      jwt:
        enabled: ${SECURITY_ENABLED:true}


authentication:
  firebase: # For testing tokens
    testUser:
      email: moneycoltest1@mailinator.com
      userId: ${FIREBASE_TEST_USER_ID}
    signInWithCustomTokenEndpoint: https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken
    webApiKey: ${FIREBASE_WEB_API_KEY}
