version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch-moneycol-local
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - path.repo=["/usr/share/elasticsearch/backups"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esbackups:/usr/share/elasticsearch/backups
      - esplugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
volumes:
  esdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $ES_DATA_PATH
  esbackups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $ES_BACKUPS_PATH
  esplugins:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $ES_PLUGINS_PATH
