apiVersion: v1
appVersion: 1.0.0
description: Data collection engine for catalog building
engine: gotpl
maintainers:
- email: moneycol@moneycol.com
  name: moneycol
name: moneycol-data-collector
version: 1.0.0
