apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
  minReadySeconds: 10
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /.well-known/apollo/server-health
              port: 4000
            initialDelaySeconds: 5
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          env:
            - name: "ENV"
              value: {{ .Values.env }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP

          resources:
            limits:
              cpu: 700m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi

      nodeSelector:
        cloud.google.com/gke-nodepool: "{{ .Values.project }}-{{ .Values.env }}-applications-pool"
