apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: moneycol-server-by-host
  labels:
    app: moneycol-server
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/rewrite-target: /graphql
spec:
  rules:
  - host: graphql.moneycol.ml
    http:
      paths:
      - backend:
          serviceName: "moneycolserver-nodeport"
          servicePort: http
        path: /