substitutions:
  _MODULE_NAME: "data-collector-base"
  _VERSION: "0.1.0"
  _SHORT_SHA: "$SHORT_SHA"
  _DOCKERFILE_PATH: "."

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/${_MODULE_NAME}:${_VERSION}-${_SHORT_SHA}', '-f', '/workspace/${_DOCKERFILE_PATH}/Dockerfile.base', '/workspace/${_DOCKERFILE_PATH}' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/${_MODULE_NAME}:${_VERSION}-${_SHORT_SHA}']

images:
  - 'eu.gcr.io/$PROJECT_ID/${_MODULE_NAME}:${_VERSION}-${_SHORT_SHA}'