apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: moneycol-server-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: moneycolserver.localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: moneycolserver
          servicePort: 80