package com.moneycol.indexer.indexing;

import com.moneycol.indexer.infra.connectivity.ElasticSearchDiscoveryClient;
import com.moneycol.indexer.infra.connectivity.ElasticSearchEndpoint;
import com.moneycol.indexer.infra.connectivity.InGkeElasticSearchDiscoveryClient;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class ElasticSearchDiscoveryClientTest {

    // This test passes if the kubeconfig file has already a token and it's not generated inside the code
    @Test
    public void findsInternalIpAndPortForElasticSearchService() {
        String serviceName = "elasticsearch-nodeport";
        String namespace = "default";
        // This file should've generated by operation authenticate() on the GkeClient
        String kubeConfigPath = "/tmp/kubeconfig.yaml";

        ElasticSearchDiscoveryClient elasticSearchDiscoveryClient = new InGkeElasticSearchDiscoveryClient();
        ElasticSearchEndpoint elasticSearchEndpoint = elasticSearchDiscoveryClient.obtainEndpoint();

        assertThat(elasticSearchEndpoint.getEndpoint()).isNotNull();
        assertThat(elasticSearchEndpoint.port()).isEqualTo("30200");
    }
}
