apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.name" . }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ template "elasticsearch.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "elasticsearch.name" . }}
  ports:
  - name: http
    port: 80
    targetPort: 9200
  type: ClusterIP