project: moneycol
env: dev
image:
  # registry: docker.elastic.co
  # repository: elasticsearch/elasticsearch
  # tag: 6.5.0
  # gcr.io/moneycol/elasticsearch:0.1.0-f4c16b8
  registry: gcr.io
  repository: moneycol/elasticsearch
  tag: 0.1.0-f4c16b8
  pullPolicy: IfNotPresent

configmap:
  name: elasticsearch-config

replicaCount: 1
