on:
  push:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'server/**/**.ts'
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY_TEST }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install Dependencies
      working-directory: server
      run: yarn
    - name: Run GraphQL Tests
      working-directory: packages/graphql
      run: yarn test